// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAC4a98iVtr44YnwX7PEqHzJWBYjP9yck',
    appId: '1:832587200514:web:37ef9c01d21c768e614f1b',
    messagingSenderId: '832587200514',
    projectId: 'trackngo-d7aa0',
    authDomain: 'trackngo-d7aa0.firebaseapp.com',
    storageBucket: 'trackngo-d7aa0.appspot.com',
    measurementId: 'G-43389GJF82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ycGH0gSWS2psX9OFz2cKbKAUWfxUzIU',
    appId: '1:832587200514:android:10113cf4750a09f7614f1b',
    messagingSenderId: '832587200514',
    projectId: 'trackngo-d7aa0',
    storageBucket: 'trackngo-d7aa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoEvfCYSY0bTzqmRZNxxQfsY3i1vR7Cog',
    appId: '1:832587200514:ios:8f6f6028a35af54e614f1b',
    messagingSenderId: '832587200514',
    projectId: 'trackngo-d7aa0',
    storageBucket: 'trackngo-d7aa0.appspot.com',
    iosClientId: '832587200514-jg4ja6sajkh3cstnegqd2goa13beh5nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackngo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoEvfCYSY0bTzqmRZNxxQfsY3i1vR7Cog',
    appId: '1:832587200514:ios:8f6f6028a35af54e614f1b',
    messagingSenderId: '832587200514',
    projectId: 'trackngo-d7aa0',
    storageBucket: 'trackngo-d7aa0.appspot.com',
    iosClientId: '832587200514-jg4ja6sajkh3cstnegqd2goa13beh5nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackngo',
  );
}
